[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding = { x = 5, y = 5 }
opacity = 0.9

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 16

[terminal]
shell = "/usr/bin/fish"

[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml"
]
